# Numpy

* faster 
* uses relatively less memory to store data 
* provides efficient storage

In [1]:
import numpy as np

In [5]:
myarr = np.array( [1,2,3,6,32,7] )

In [7]:
type(myarr)

numpy.ndarray

**specifying data types**

In [10]:
myarr = np.array ( [1,2,3,6,32,7], np.int8 ) #only 8 byte array of int

In [11]:
myarr

array([ 1,  2,  3,  6, 32,  7], dtype=int8)

In [13]:
myarr[1]

2

**2D arrays**

In [14]:
matrix = np.array ( [[1,2,3,4]] )

In [15]:
type(matrix)

numpy.ndarray

In [18]:
matrix[0,1]

2

***get shape of matrix**

In [20]:
matrix.shape # 1 row 4 cols

(1, 4)

**changing values**

In [21]:
matrix[0,1] = 45

In [22]:
matrix

array([[ 1, 45,  3,  4]])

## array creation methods in numpy

### conversion form python objects like list, tuple ...

In [28]:
listArr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [29]:
listArr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
listArr.shape

(3, 3)

In [31]:
listArr.dtype

dtype('int32')

### intrinsic numpy creation objects

**```zeros()``` method**

In [33]:
zeros = np.zeros((2,5)) #creates an array of 2x5 with zero value

In [34]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**```arange()``` method**

In [37]:
rng = np.arange(15) #aray from 1 to 15

In [38]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**```linspace()``` method**

In [47]:
lspace = np.linspace(1,4,4) #array of 4 elements from 1 to 4 that are linearly spaced 

In [48]:
lspace

array([1., 2., 3., 4.])

In [51]:
lspace = np.linspace(1,4,5) #array of 5 elements from 1 to 4 that are linearly spaced 

In [50]:
lspace

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

**```empty()``` method**

In [54]:
emp = np.empty((4,6)) #empty array of 4x6 with random elements

In [55]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.29061414e-306, 7.56587585e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 1.33511018e-306, 6.23057689e-307,
        1.86921279e-306, 8.90098127e-307, 1.78020848e-306],
       [1.60219035e-306, 1.42418172e-306, 2.04712906e-306,
        7.56589622e-307, 1.11258277e-307, 8.90111708e-307]])

**```empty_like()``` method**

In [59]:
emp_like = np.empty_like(lspace) #copies lspace array 

In [60]:
emp_like

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

**```identity()``` method**

In [63]:
id = np.identity(45) #identity matrix of 45x45

In [64]:
id

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [65]:
id.shape

(45, 45)

**```reshape()``` method**

In [72]:
arr = np.arange(99) #arrange a array of 99 elements  from 0 to 98

In [73]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [78]:
arr = arr.reshape(3,33) #reshapes it to a 2D array with 3X33 shape

In [79]:
arr.shape

(3, 33)

**```ravel()``` method**

In [83]:
arr = arr.ravel() #converts back to 1D array

In [85]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [84]:
arr.shape

(99,)

## Numpy Axix